using LibraryManagementSystem.Data;
using LibraryManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagementSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EBooksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;

        public EBooksController(
            ApplicationDbContext context,
            IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }


        // =========================
        // GET: EBooks
        // =========================

        public async Task<IActionResult> Index()
        {
            var ebooks = await _context.EBooks
                .OrderByDescending(e => e.UploadedAt)
                .ToListAsync();

            return View(ebooks);
        }


        // =========================
        // GET: EBooks/Create
        // =========================

        public async Task<IActionResult> Create()
        {
            await LoadCategories();

            return View();
        }


        // =========================
        // POST: EBooks/Create
        // =========================

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            EBook ebook,
            IFormFile? pdfFile)
        {
            // FileName and FilePath are generated by the system
            ModelState.Remove(nameof(EBook.FileName));
            ModelState.Remove(nameof(EBook.FilePath));


            // =========================
            // PDF VALIDATION
            // =========================

            if (pdfFile == null || pdfFile.Length == 0)
            {
                ModelState.AddModelError(
                    "pdfFile",
                    "Please select a PDF file.");
            }
            else
            {
                string extension =
                    Path.GetExtension(pdfFile.FileName)
                        .ToLowerInvariant();

                if (extension != ".pdf")
                {
                    ModelState.AddModelError(
                        "pdfFile",
                        "Only PDF files are allowed.");
                }
            }


            // =========================
            // MODEL VALIDATION
            // =========================

            if (!ModelState.IsValid)
            {
                await LoadCategories(ebook.Category);

                return View(ebook);
            }


            // =========================
            // CREATE UPLOAD FOLDER
            // =========================

            var uploadFolder = Path.Combine(
                _environment.WebRootPath,
                "ebooks");

            if (!Directory.Exists(uploadFolder))
            {
                Directory.CreateDirectory(uploadFolder);
            }


            // =========================
            // CREATE UNIQUE FILE NAME
            // =========================

            var uniqueFileName =
                Guid.NewGuid().ToString("N") + ".pdf";

            var physicalFilePath = Path.Combine(
                uploadFolder,
                uniqueFileName);


            // =========================
            // SAVE PDF FILE
            // =========================

            using (var stream = new FileStream(
                physicalFilePath,
                FileMode.Create))
            {
                await pdfFile!.CopyToAsync(stream);
            }


            // =========================
            // SAVE FILE INFORMATION
            // =========================

            ebook.FileName =
                Path.GetFileName(pdfFile!.FileName);

            ebook.FilePath =
                "/ebooks/" + uniqueFileName;

            ebook.UploadedAt = DateTime.Now;


            // =========================
            // SAVE TO DATABASE
            // =========================

            _context.EBooks.Add(ebook);

            await _context.SaveChangesAsync();


            TempData["Success"] =
                "E-Book uploaded successfully.";


            return RedirectToAction(nameof(Index));
        }


        // =========================
        // LOAD CATEGORIES
        // =========================

        private async Task LoadCategories(
            string? selectedCategory = null)
        {
            var categories = await _context.Categories
                .OrderBy(c => c.Name)
                .ToListAsync();

            ViewBag.Categories = new SelectList(
                categories,
                "Name",
                "Name",
                selectedCategory);
        }


        // =========================
        // GET: EBooks/Delete/5
        // =========================

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ebook = await _context.EBooks
                .FirstOrDefaultAsync(e => e.Id == id);

            if (ebook == null)
            {
                return NotFound();
            }

            return View(ebook);
        }


        // =========================
        // POST: EBooks/Delete/5
        // =========================

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ebook = await _context.EBooks
                .FirstOrDefaultAsync(e => e.Id == id);

            if (ebook == null)
            {
                return NotFound();
            }


            // Delete physical PDF file

            if (!string.IsNullOrEmpty(ebook.FilePath))
            {
                var physicalPath = Path.Combine(
                    _environment.WebRootPath,
                    ebook.FilePath.TrimStart('/')
                                      .Replace(
                                          '/',
                                          Path.DirectorySeparatorChar));

                if (System.IO.File.Exists(physicalPath))
                {
                    System.IO.File.Delete(physicalPath);
                }
            }


            // Delete database record

            _context.EBooks.Remove(ebook);

            await _context.SaveChangesAsync();


            TempData["Success"] =
                "E-Book deleted successfully.";


            return RedirectToAction(nameof(Index));
        }
    }
}
